# Generated by Django 4.1.7 on 2023-03-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Appointment Date')),
                ('description', models.TextField(max_length=250)),
                ('faarequired', models.BooleanField(default=False)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plane')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
